(()=>{const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];const loader=$('#loader'),fill=$('#loaderFill'),pct=$('#loaderPercent'),status=$('#loaderStatus'),doors=$('#doorTransition'),doorMessage=$('#doorMessage');
const phrases=['The ancient grove is stirring…','Fireflies are lighting the path…','The woodland archive is awakening…','The rune gate is opening…','The realm awaits.'];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let n=0;
let doorArrival=false;
try{doorArrival=sessionStorage.getItem('woodlandDoorArrival')==='1';if(doorArrival)sessionStorage.removeItem('woodlandDoorArrival')}catch(_){}
function setDoorMessage(text){if(doorMessage)doorMessage.textContent=text}
function clearDoorClasses(){if(doors)doors.classList.remove('active','open','sealed','closing','flash','text-glow','preclosing')}
function prepareClosedArrival(message='WELCOME TO THE REALM'){if(!doors)return;setDoorMessage(message);doors.classList.remove('open','closing','flash','text-glow','preclosing');doors.classList.add('active','sealed');void doors.offsetWidth}
function openArrivalDoors(){if(!doors){document.body.classList.remove('loading','transitioning');return}document.body.classList.add('transitioning');prepareClosedArrival('WELCOME TO THE REALM');setTimeout(()=>doors.classList.add('text-glow'),reduced?20:210);setTimeout(()=>doors.classList.add('flash'),reduced?40:470);setTimeout(()=>doors.classList.add('open'),reduced?70:690);setTimeout(()=>doors.classList.remove('sealed'),reduced?90:930);setTimeout(()=>{clearDoorClasses();document.body.classList.remove('transitioning')},reduced?180:1710)}
function revealRealm(){if(loader){loader.classList.add('hidden');setTimeout(()=>loader.remove(),reduced?20:720)}document.body.classList.remove('loading')}
function finishLoader(){n=100;if(fill)fill.style.width='100%';if(pct)pct.textContent='100%';if(status)status.textContent=phrases[4];if(loader)loader.classList.add('complete');setTimeout(revealRealm,reduced?80:1050)}

/* Rich loader motes based on the original BRASHEXODUS woodland atmosphere. */
if(loader&&!reduced){const layer=loader.querySelector('.loader-atmosphere');if(layer&&!layer.querySelector('.loader-spark')){const frag=document.createDocumentFragment();const count=innerWidth<700?34:74;for(let i=0;i<count;i++){const mote=document.createElement('b');mote.className='loader-spark '+(i%5===0?'gold':'green');mote.style.setProperty('--x',`${Math.random()*100}%`);mote.style.setProperty('--y',`${Math.random()*100}%`);mote.style.setProperty('--size',`${1.2+Math.random()*3.4}px`);mote.style.setProperty('--duration',`${5+Math.random()*10}s`);mote.style.setProperty('--delay',`${-Math.random()*12}s`);mote.style.setProperty('--drift',`${-70+Math.random()*140}px`);frag.appendChild(mote)}layer.appendChild(frag)}}

/* Keep first paint covered until the correct overlay has been initialized. */
if(doorArrival){if(loader)loader.remove();document.body.classList.remove('loading');document.body.classList.add('transitioning');prepareClosedArrival('WELCOME TO THE REALM');requestAnimationFrame(()=>requestAnimationFrame(()=>{document.documentElement.classList.remove('wr-boot','door-arrival');setTimeout(openArrivalDoors,reduced?20:160)}))}else if(loader){requestAnimationFrame(()=>document.documentElement.classList.remove('wr-boot'));const started=performance.now(),duration=reduced?700:4650;const frame=now=>{const raw=Math.min(1,(now-started)/duration),eased=1-Math.pow(1-raw,3);n=Math.round(eased*100);if(fill)fill.style.width=n+'%';if(pct)pct.textContent=n+'%';if(status)status.textContent=phrases[Math.min(4,Math.floor(n/21))];if(raw<1)requestAnimationFrame(frame);else finishLoader()};requestAnimationFrame(frame)}else{document.body.classList.remove('loading');document.documentElement.classList.remove('wr-boot')}

/* Portfolio-style ambient atmosphere: stars, fireflies and tiny drifting motes. */
(function buildRealmAtmosphere(){if(reduced||document.querySelector('.realm-atmosphere-canvas'))return;const haze=document.createElement('div');haze.className='realm-forest-haze';haze.setAttribute('aria-hidden','true');const canvas=document.createElement('canvas');canvas.className='realm-atmosphere-canvas';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);document.body.prepend(haze);const ctx=canvas.getContext('2d',{alpha:true});if(!ctx)return;const saveData=navigator.connection?.saveData===true;const lowMemory=Number(navigator.deviceMemory||8)<=4;const lowPower=saveData||lowMemory||innerWidth<700;let dpr=1,w=0,h=0,last=0,raf=0,stars=[],flies=[],motes=[];function resize(){dpr=Math.min(devicePixelRatio||1,lowPower?1:1.5);w=innerWidth;h=innerHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const sc=lowPower?Math.min(55,Math.floor(w/16)):Math.min(130,Math.floor(w/9));const fc=lowPower?9:Math.min(30,Math.floor(w/44));const mc=lowPower?8:18;stars=Array.from({length:sc},()=>({x:Math.random()*w,y:Math.random()*h*.88,r:Math.random()*1.25+.2,a:Math.random()*.62+.12,p:Math.random()*6.28,s:Math.random()*.85+.3}));flies=Array.from({length:fc},()=>({x:Math.random()*w,y:h*(.28+Math.random()*.7),r:Math.random()*1.5+.65,p:Math.random()*6.28,v:Math.random()*.16+.05}));motes=Array.from({length:mc},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.7+.7,v:Math.random()*.16+.06,d:(Math.random()-.5)*.14,p:Math.random()*6.28}))}function draw(now){if(now-last<(lowPower?32:16)){raf=requestAnimationFrame(draw);return}last=now;const t=now/1000;ctx.clearRect(0,0,w,h);for(const s of stars){const a=s.a*(.5+Math.sin(t*s.s+s.p)*.36);ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fillStyle=`rgba(244,236,192,${Math.max(.03,a)})`;ctx.fill()}for(const f of flies){f.x+=Math.sin(t*.7+f.p)*f.v;f.y+=Math.cos(t*.5+f.p)*f.v*.45;const a=.18+(Math.sin(t*1.45+f.p)+1)*.23;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,Math.PI*2);ctx.fillStyle=`rgba(167,230,112,${a})`;ctx.shadowBlur=13;ctx.shadowColor='rgba(151,224,102,.72)';ctx.fill();ctx.shadowBlur=0}for(const m of motes){m.y-=m.v;m.x+=m.d+Math.sin(t+m.p)*.07;if(m.y<-8){m.y=h+8;m.x=Math.random()*w}ctx.save();ctx.translate(m.x,m.y);ctx.rotate(t*.18+m.p);ctx.fillStyle='rgba(198,178,104,.18)';ctx.fillRect(-m.r/2,-m.r,m.r,m.r*2);ctx.restore()}raf=requestAnimationFrame(draw)}resize();addEventListener('resize',resize,{passive:true});raf=requestAnimationFrame(draw);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(raf);else{last=0;raf=requestAnimationFrame(draw)}})})();

const cursor=$('#cursor');if(cursor&&matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';cursor.classList.toggle('hover',!!e.target.closest('a,button,input,select,textarea,[role="button"],.map-pin,.region-card'))},{passive:true});addEventListener('pointerdown',()=>cursor.classList.add('clicking'),{passive:true});addEventListener('pointerup',()=>cursor.classList.remove('clicking'),{passive:true})}
const header=$('.site-header'),progress=$('#pageProgress');addEventListener('scroll',()=>{if(header)header.classList.toggle('compact',scrollY>30);if(progress){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%'}},{passive:true});
const menu=$('#menu'),nav=$('#nav');if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});$$('#nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}))}
const io=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});$$('.reveal').forEach(el=>io.observe(el));


let atlasRegions={},selectedRegionId=null,activeRegionFilter='all';
const atlasGrid=$('#regionGrid'),regionSearch=$('#regionSearch');
function regionHaystack(r){return [r.name,r.status,r.summary,r.description,...(r.settlements||[]),...(r.quests||[]),...(r.creatures||[]),...(r.resources||[]),...(r.features||[])].join(' ').toLowerCase()}
function selectRegion(id,openDetail=false){const r=atlasRegions[id];if(!r)return;selectedRegionId=id;$$('.map-pin').forEach(p=>p.classList.toggle('selected',p.dataset.regionId===id));$$('.region-card').forEach(c=>c.classList.toggle('selected',c.dataset.regionId===id));const title=$('#regionTitle'),text=$('#regionText'),status=$('#regionStatus'),tags=$('#regionFeatureTags'),open=$('#openSelectedRegion');if(title)title.textContent=r.name;if(text)text.textContent=r.summary;if(status)status.textContent=r.status+(Number.isFinite(r.completion)?' • '+r.completion+'% complete':' • documented archive');if(tags)tags.innerHTML=(r.features||[]).slice(0,5).map(x=>`<span>${x}</span>`).join('');if(open)open.disabled=false;if(openDetail)showRegionDetail(id);toast('Atlas selected: '+r.name)}
function listInto(sel,items){const el=$(sel);if(el)el.innerHTML=(items||[]).map(x=>`<li>${x}</li>`).join('')}
function showRegionDetail(id){const r=atlasRegions[id];const detail=$('#regionDetail');if(!r||!detail)return;$('#detailStatus').textContent=r.status;$('#detailName').textContent=(r.icon?r.icon+' ':'')+r.name;$('#detailDescription').textContent=r.description;$('#detailCompletion').textContent=Number.isFinite(r.completion)?r.completion+'%':'ARCHIVE';$('#detailDanger').textContent='Danger: '+r.danger;requestAnimationFrame(()=>$('#detailCompletionFill').style.width=(Number.isFinite(r.completion)?r.completion:100)+'%');listInto('#detailSettlements',r.settlements);listInto('#detailQuests',r.quests);listInto('#detailCreatures',r.creatures);listInto('#detailResources',r.resources);$('#detailFeatures').innerHTML=(r.features||[]).map(x=>`<span>${x}</span>`).join('');$('#detailGallery').innerHTML=(r.gallery||[]).map((src,i)=>`<figure><img src="${src}" alt="${r.name} environment reference ${i+1}" loading="lazy"><figcaption>${r.name} • field view ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('');detail.hidden=false;detail.scrollIntoView({behavior:'smooth',block:'start'})}
function renderRegionGrid(){if(!atlasGrid)return;const q=(regionSearch?.value||'').trim().toLowerCase();const rows=Object.entries(atlasRegions).filter(([id,r])=>(activeRegionFilter==='all'||r.status===activeRegionFilter)&&(!q||regionHaystack(r).includes(q)));atlasGrid.innerHTML=rows.map(([id,r])=>`<article class="region-card ${selectedRegionId===id?'selected':''}" data-region-id="${id}" tabindex="0"><div class="region-card-top"><span class="region-icon">${r.icon||'◆'}</span><span class="region-state">${r.status}</span></div><h3>${r.name}</h3><p>${r.summary}</p><div class="region-card-progress"><i style="width:${Number.isFinite(r.completion)?r.completion:100}%"></i></div><div class="region-card-meta"><span>${Number.isFinite(r.completion)?r.completion+'% built':'Documented archive'}</span><span>Danger: ${r.danger}</span></div><div class="region-card-counts"><span>${(r.settlements||[]).length} settlements</span><span>${(r.quests||[]).length} quests</span><span>${(r.creatures||[]).length} creatures</span></div><button type="button" class="text-link region-card-open">View atlas entry →</button></article>`).join('');const count=$('#atlasResultCount');if(count)count.textContent=rows.length+' region'+(rows.length===1?'':'s');$$('.region-card',atlasGrid).forEach(card=>{const activate=()=>selectRegion(card.dataset.regionId,true);card.addEventListener('click',e=>{if(e.target.closest('button')||e.target===card)activate();else activate()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})});if(!rows.length)atlasGrid.innerHTML='<div class="atlas-empty"><strong>No paths found.</strong><span>Try a different search or development filter.</span></div>'}
if(atlasGrid||$$('.map-pin').length){fetch('data/regions.json').then(r=>r.json()).then(d=>{atlasRegions=d.regions||{};renderRegionGrid();$$('.map-pin').forEach(pin=>pin.addEventListener('click',()=>selectRegion(pin.dataset.regionId,false)));}).catch(()=>{if(atlasGrid)atlasGrid.innerHTML='<div class="atlas-empty"><strong>The atlas could not be opened.</strong><span>Check data/regions.json when testing locally.</span></div>'})}
if(regionSearch)regionSearch.addEventListener('input',renderRegionGrid);
$$('.region-filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.region-filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeRegionFilter=btn.dataset.regionFilter||'all';renderRegionGrid()}));
$('#openSelectedRegion')?.addEventListener('click',()=>selectedRegionId&&showRegionDetail(selectedRegionId));
$('#closeRegionDetail')?.addEventListener('click',()=>{const d=$('#regionDetail');if(d){d.hidden=true;$('.atlas-map')?.scrollIntoView({behavior:'smooth',block:'center'})}});


const bc=$('#builderClass'),bp=$('#builderProfession'),bh=$('#builderHomeland'),bs=$('#builderStyle');function updateBuilder(){if(!bc||!bp||!bh||!bs)return;$('#builderTitle').textContent=bc.value+' of '+bh.value;$('#builderSummary').textContent='A '+bc.value+' from '+bh.value+' following the '+bp.value+' profession with a '+bs.value+'-focused journey.';$('#builderTags').innerHTML=[bc.value,bp.value,bh.value,bs.value].map(x=>`<span>${x}</span>`).join('')}[bc,bp,bh,bs].filter(Boolean).forEach(x=>x.addEventListener('change',updateBuilder));updateBuilder();
if($('#developmentRegionGrid')){fetch('data/regions.json').then(r=>r.json()).then(d=>{const rows=Object.values(d.regions||{});$('#developmentRegionGrid').innerHTML=rows.map(r=>`<article class="development-card"><div class="region-card-top"><span class="region-icon">${r.icon||'◆'}</span><span class="region-state">${r.status}</span></div><h3>${r.name}</h3><p>${r.summary}</p><div class="region-card-progress"><i style="width:${Number.isFinite(r.completion)?r.completion:100}%"></i></div><div class="region-card-meta"><span>${Number.isFinite(r.completion)?r.completion+'% complete':'Documented archive'}</span><a class="text-link" href="world.html">Open atlas →</a></div></article>`).join('')})}
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');clearTimeout(window.__wrToast);window.__wrToast=setTimeout(()=>t.classList.remove('show'),2400)}
fetch('data/site.json').then(r=>r.json()).then(d=>{const set=(s,v)=>{$$(s).forEach(el=>el.textContent=v)};set('#serverStatus',d.serverStatus||'In Development');set('#mcVersion',d.minecraftVersion||'1.21');set('#bedrockStatus',d.bedrockSupported||'To Be Confirmed');set('#playerCount',(d.playerCount||'—')+' / '+(d.maxPlayers||'—'));const c=Number(d.worldCompletion)||0;set('#completionValue',c+'%');$$('#completionFill').forEach(el=>requestAnimationFrame(()=>el.style.width=c+'%'));if(d.serverAddress&&d.serverAddress!=='Coming Soon')set('#serverAddress',d.serverAddress);[['#discordJoin',d.discordUrl],['#pmcLink',d.planetMinecraftUrl],['#githubLink',d.githubUrl],['#githubCard',d.githubUrl]].forEach(([s,u])=>{$$(s).forEach(el=>{if(u)el.href=u})})}).catch(()=>{$$('#completionFill').forEach(el=>el.style.width='72%')});
$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const cat=btn.dataset.filter;$$('.quest-grid article').forEach(card=>card.classList.toggle('hidden-filter',cat!=='all'&&card.dataset.category!==cat))}));
$$('a[href]').forEach(a=>{const href=a.getAttribute('href');if(!href||href.startsWith('http')||href.startsWith('mailto:')||href.startsWith('#'))return;a.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||a.target==='_blank')return;e.preventDefault();if(!doors){location.href=href;return}document.body.classList.add('transitioning');setDoorMessage('TRAVELING THROUGH THE REALM');clearDoorClasses();/* Stage 1: make the off-screen doors visible without covering the center. */doors.classList.add('active','open','preclosing');void doors.offsetWidth;/* Stage 2: after the open state has actually painted, slide both panels inward. */setTimeout(()=>{doors.classList.add('closing');doors.classList.remove('open','preclosing')},reduced?20:90);/* Stage 3: only make the backing opaque after the doors have reached the seam. */setTimeout(()=>doors.classList.add('sealed'),reduced?70:1080);setTimeout(()=>doors.classList.add('text-glow'),reduced?90:1210);setTimeout(()=>{try{sessionStorage.setItem('woodlandDoorArrival','1')}catch(_){}location.href=href},reduced?190:1600)})});


/* Restored hand-drawn leaf field from the BRASHEXODUS portfolio. */
(()=>{const assets=['broadleaf-01.png','broadleaf-02.png','broadleaf-03.png','broadleaf-04.png','broadleaf-05.png','broadleaf-06.png','spruce-a-01.png','spruce-a-02.png','spruce-a-03.png','spruce-a-04.png','spruce-a-05.png','spruce-b-01.png','spruce-b-02.png','spruce-b-03.png','spruce-b-04.png','spruce-b-05.png','spruce-c-01.png','spruce-c-02.png','spruce-c-03.png','spruce-c-04.png'];if(reduced||navigator.connection?.saveData===true||$('.custom-leaf-field'))return;const field=document.createElement('div');field.className='custom-leaf-field';field.setAttribute('aria-hidden','true');const compact=matchMedia('(max-width:760px)').matches,lowMemory=Number(navigator.deviceMemory||8)<=4,count=compact?12:lowMemory?16:22,frag=document.createDocumentFragment();for(let i=0;i<count;i++){const leaf=document.createElement('img'),size=compact?24+Math.random()*25:28+Math.random()*46,opacity=.38+Math.random()*.47,duration=13+Math.random()*17,delay=-(Math.random()*duration),startX=-6+Math.random()*106,drift=-120+Math.random()*240,sway=22+Math.random()*65,rotation=(Math.random()<.5?-1:1)*(300+Math.random()*620);leaf.className=`custom-leaf ${size>57?'is-near':size<37?'is-far':''}`;leaf.alt='';leaf.decoding='async';leaf.draggable=false;leaf.src=`assets/leaves/${assets[i%assets.length]}`;leaf.style.setProperty('--leaf-size',`${size.toFixed(1)}px`);leaf.style.setProperty('--leaf-opacity',opacity.toFixed(2));leaf.style.setProperty('--leaf-duration',`${duration.toFixed(2)}s`);leaf.style.setProperty('--leaf-delay',`${delay.toFixed(2)}s`);leaf.style.setProperty('--leaf-start-x',`${startX.toFixed(2)}vw`);leaf.style.setProperty('--leaf-drift',`${drift.toFixed(1)}px`);leaf.style.setProperty('--leaf-sway',`${sway.toFixed(1)}px`);leaf.style.setProperty('--leaf-rotation',`${rotation.toFixed(0)}deg`);frag.appendChild(leaf)}field.appendChild(frag);document.body.prepend(field);document.addEventListener('visibilitychange',()=>field.querySelectorAll('.custom-leaf').forEach(leaf=>leaf.style.animationPlayState=document.hidden?'paused':'running'));
if(matchMedia('(pointer:fine)').matches){let px=-9999,py=-9999,windRaf=0;const leaves=[...field.querySelectorAll('.custom-leaf')],radius=155;const applyWind=()=>{windRaf=0;for(const leaf of leaves){const r=leaf.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=cx-px,dy=cy-py,dist=Math.hypot(dx,dy);if(dist<radius){const force=(1-dist/radius),inv=dist?1/dist:1,wx=dx*inv*force*74,wy=dy*inv*force*48-18*force;leaf.style.setProperty('--mouse-wind-x',wx.toFixed(1)+'px');leaf.style.setProperty('--mouse-wind-y',wy.toFixed(1)+'px');leaf.style.setProperty('--mouse-wind-rot',(wx*.18).toFixed(1)+'deg')}else{leaf.style.setProperty('--mouse-wind-x','0px');leaf.style.setProperty('--mouse-wind-y','0px');leaf.style.setProperty('--mouse-wind-rot','0deg')}}};addEventListener('pointermove',e=>{px=e.clientX;py=e.clientY;if(!windRaf)windRaf=requestAnimationFrame(applyWind)},{passive:true});addEventListener('pointerleave',()=>{px=py=-9999;if(!windRaf)windRaf=requestAnimationFrame(applyWind)},{passive:true})}})();

/* Restored functional fantasy scrollbar. */
(()=>{const fine=matchMedia('(pointer:fine)');let bar,rail,thumb,dragging=false,dragOffset=0,raf=0;const maxScroll=()=>Math.max(0,document.documentElement.scrollHeight-innerHeight),travel=()=>Math.max(0,rail.clientHeight-thumb.offsetHeight),enabled=()=>fine.matches&&innerWidth>760&&maxScroll()>10;function update(){raf=0;if(!bar)return;const on=enabled();bar.hidden=!on;document.documentElement.classList.toggle('woodland-custom-scrollbar',on);if(!on)return;const y=(maxScroll()?Math.min(1,Math.max(0,scrollY/maxScroll())):0)*travel();thumb.style.transform=`translate(-50%, ${y}px)`}function req(){if(!raf)raf=requestAnimationFrame(update)}function fromPointer(y,smooth=false){const rect=rail.getBoundingClientRect(),t=travel();if(!t)return;const top=Math.min(t,Math.max(0,y-rect.top-dragOffset)),target=(top/t)*maxScroll();scrollTo({top:target,behavior:smooth&&!reduced?'smooth':'auto'})}function build(){if($('.woodland-fantasy-scrollbar'))return;bar=document.createElement('div');bar.className='woodland-fantasy-scrollbar';bar.setAttribute('aria-hidden','true');bar.innerHTML='<div class="woodland-fantasy-scrollbar__track"><div class="woodland-fantasy-scrollbar__rail"><div class="woodland-fantasy-scrollbar__thumb"></div></div></div>';document.body.appendChild(bar);rail=$('.woodland-fantasy-scrollbar__rail',bar);thumb=$('.woodland-fantasy-scrollbar__thumb',bar);thumb.addEventListener('pointerdown',e=>{if(!enabled())return;dragging=true;bar.classList.add('is-dragging');thumb.setPointerCapture(e.pointerId);dragOffset=e.clientY-thumb.getBoundingClientRect().top;e.preventDefault()});thumb.addEventListener('pointermove',e=>{if(dragging){fromPointer(e.clientY);e.preventDefault()}});const stop=e=>{if(!dragging)return;dragging=false;bar.classList.remove('is-dragging');try{thumb.releasePointerCapture(e.pointerId)}catch(_){}};thumb.addEventListener('pointerup',stop);thumb.addEventListener('pointercancel',stop);rail.addEventListener('pointerdown',e=>{if(e.target===thumb||!enabled())return;dragOffset=thumb.offsetHeight/2;fromPointer(e.clientY,true);e.preventDefault()});addEventListener('scroll',req,{passive:true});addEventListener('resize',req,{passive:true});new ResizeObserver(req).observe(document.documentElement);req()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',build,{once:true}):build()})();
})();