(()=>{const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];const loader=$('#loader'),fill=$('#loaderFill'),pct=$('#loaderPercent'),status=$('#loaderStatus'),doors=$('#doorTransition'),doorMessage=$('#doorMessage');
const phrases=['The ancient grove is stirring…','Fireflies are lighting the path…','The woodland archive is awakening…','The rune gate is opening…','The realm awaits.'];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let n=0;
let doorArrival=false;
try{doorArrival=sessionStorage.getItem('woodlandDoorArrival')==='1';if(doorArrival)sessionStorage.removeItem('woodlandDoorArrival')}catch(_){}
function setDoorMessage(text){if(doorMessage)doorMessage.textContent=text}
function sealDoors(message='TRAVELING THROUGH THE REALM'){if(!doors)return;setDoorMessage(message);doors.classList.add('active','sealed');doors.classList.remove('open','text-glow','flash','closing');void doors.offsetWidth}
function flashAndOpenDoors(){if(!doors){document.body.classList.remove('loading','transitioning');return}document.body.classList.add('transitioning');doors.classList.add('active','sealed');doors.classList.remove('open','closing');setDoorMessage('WELCOME TO THE REALM');setTimeout(()=>doors.classList.add('text-glow'),reduced?20:260);setTimeout(()=>doors.classList.add('flash'),reduced?40:620);setTimeout(()=>doors.classList.add('open'),reduced?70:820);setTimeout(()=>doors.classList.remove('sealed'),reduced?90:1030);setTimeout(()=>{doors.classList.remove('active','open','sealed','text-glow','flash','closing');document.body.classList.remove('transitioning')},reduced?220:1900)}
function revealRealm(){if(loader){loader.classList.add('hidden');setTimeout(()=>loader.remove(),reduced?20:520)}document.body.classList.remove('loading');setTimeout(()=>{sealDoors('WELCOME TO THE REALM');flashAndOpenDoors()},reduced?25:560)}
function finishLoader(){n=100;if(fill)fill.style.width='100%';if(pct)pct.textContent='100%';if(status)status.textContent=phrases[4];setTimeout(revealRealm,reduced?40:460)}
if(doorArrival){if(loader)loader.remove();document.documentElement.classList.remove('door-arrival');document.body.classList.remove('loading');document.body.classList.add('transitioning');sealDoors('WELCOME TO THE REALM');setTimeout(flashAndOpenDoors,reduced?20:260)}else if(loader){const started=performance.now(),duration=reduced?650:4300;const frame=now=>{const raw=Math.min(1,(now-started)/duration),eased=1-Math.pow(1-raw,3);n=Math.round(eased*100);if(fill)fill.style.width=n+'%';if(pct)pct.textContent=n+'%';if(status)status.textContent=phrases[Math.min(4,Math.floor(n/21))];if(raw<1)requestAnimationFrame(frame);else finishLoader()};requestAnimationFrame(frame)}else{document.body.classList.remove('loading');setTimeout(()=>{sealDoors('WELCOME TO THE REALM');flashAndOpenDoors()},40)}
const cursor=$('#cursor');if(cursor&&matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';cursor.classList.toggle('hover',!!e.target.closest('a,button,input,select,textarea,[role="button"],.map-pin,.region-card'))},{passive:true});addEventListener('pointerdown',()=>cursor.classList.add('clicking'),{passive:true});addEventListener('pointerup',()=>cursor.classList.remove('clicking'),{passive:true})}
const header=$('.site-header'),progress=$('#pageProgress');addEventListener('scroll',()=>{if(header)header.classList.toggle('compact',scrollY>30);if(progress){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%'}},{passive:true});
const menu=$('#menu'),nav=$('#nav');if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});$$('#nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}))}
const io=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});$$('.reveal').forEach(el=>io.observe(el));


let atlasRegions={},selectedRegionId=null,activeRegionFilter='all';
const atlasGrid=$('#regionGrid'),regionSearch=$('#regionSearch');
function regionHaystack(r){return [r.name,r.status,r.summary,r.description,...(r.settlements||[]),...(r.quests||[]),...(r.creatures||[]),...(r.resources||[]),...(r.features||[])].join(' ').toLowerCase()}
function selectRegion(id,openDetail=false){const r=atlasRegions[id];if(!r)return;selectedRegionId=id;$$('.map-pin').forEach(p=>p.classList.toggle('selected',p.dataset.regionId===id));$$('.region-card').forEach(c=>c.classList.toggle('selected',c.dataset.regionId===id));const title=$('#regionTitle'),text=$('#regionText'),status=$('#regionStatus'),tags=$('#regionFeatureTags'),open=$('#openSelectedRegion');if(title)title.textContent=r.name;if(text)text.textContent=r.summary;if(status)status.textContent=r.status+' • '+r.completion+'% complete';if(tags)tags.innerHTML=(r.features||[]).slice(0,5).map(x=>`<span>${x}</span>`).join('');if(open)open.disabled=false;if(openDetail)showRegionDetail(id);toast('Atlas selected: '+r.name)}
function listInto(sel,items){const el=$(sel);if(el)el.innerHTML=(items||[]).map(x=>`<li>${x}</li>`).join('')}
function showRegionDetail(id){const r=atlasRegions[id];const detail=$('#regionDetail');if(!r||!detail)return;$('#detailStatus').textContent=r.status;$('#detailName').textContent=(r.icon?r.icon+' ':'')+r.name;$('#detailDescription').textContent=r.description;$('#detailCompletion').textContent=r.completion+'%';$('#detailDanger').textContent='Danger: '+r.danger;requestAnimationFrame(()=>$('#detailCompletionFill').style.width=r.completion+'%');listInto('#detailSettlements',r.settlements);listInto('#detailQuests',r.quests);listInto('#detailCreatures',r.creatures);listInto('#detailResources',r.resources);$('#detailFeatures').innerHTML=(r.features||[]).map(x=>`<span>${x}</span>`).join('');$('#detailGallery').innerHTML=(r.gallery||[]).map((src,i)=>`<figure><img src="${src}" alt="${r.name} environment reference ${i+1}" loading="lazy"><figcaption>${r.name} • field view ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('');detail.hidden=false;detail.scrollIntoView({behavior:'smooth',block:'start'})}
function renderRegionGrid(){if(!atlasGrid)return;const q=(regionSearch?.value||'').trim().toLowerCase();const rows=Object.entries(atlasRegions).filter(([id,r])=>(activeRegionFilter==='all'||r.status===activeRegionFilter)&&(!q||regionHaystack(r).includes(q)));atlasGrid.innerHTML=rows.map(([id,r])=>`<article class="region-card ${selectedRegionId===id?'selected':''}" data-region-id="${id}" tabindex="0"><div class="region-card-top"><span class="region-icon">${r.icon||'◆'}</span><span class="region-state">${r.status}</span></div><h3>${r.name}</h3><p>${r.summary}</p><div class="region-card-progress"><i style="width:${r.completion}%"></i></div><div class="region-card-meta"><span>${r.completion}% built</span><span>Danger: ${r.danger}</span></div><div class="region-card-counts"><span>${(r.settlements||[]).length} settlements</span><span>${(r.quests||[]).length} quests</span><span>${(r.creatures||[]).length} creatures</span></div><button type="button" class="text-link region-card-open">View atlas entry →</button></article>`).join('');const count=$('#atlasResultCount');if(count)count.textContent=rows.length+' region'+(rows.length===1?'':'s');$$('.region-card',atlasGrid).forEach(card=>{const activate=()=>selectRegion(card.dataset.regionId,true);card.addEventListener('click',e=>{if(e.target.closest('button')||e.target===card)activate();else activate()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})});if(!rows.length)atlasGrid.innerHTML='<div class="atlas-empty"><strong>No paths found.</strong><span>Try a different search or development filter.</span></div>'}
if(atlasGrid||$$('.map-pin').length){fetch('data/regions.json').then(r=>r.json()).then(d=>{atlasRegions=d.regions||{};renderRegionGrid();$$('.map-pin').forEach(pin=>pin.addEventListener('click',()=>selectRegion(pin.dataset.regionId,false)));}).catch(()=>{if(atlasGrid)atlasGrid.innerHTML='<div class="atlas-empty"><strong>The atlas could not be opened.</strong><span>Check data/regions.json when testing locally.</span></div>'})}
if(regionSearch)regionSearch.addEventListener('input',renderRegionGrid);
$$('.region-filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.region-filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeRegionFilter=btn.dataset.regionFilter||'all';renderRegionGrid()}));
$('#openSelectedRegion')?.addEventListener('click',()=>selectedRegionId&&showRegionDetail(selectedRegionId));
$('#closeRegionDetail')?.addEventListener('click',()=>{const d=$('#regionDetail');if(d){d.hidden=true;$('.atlas-map')?.scrollIntoView({behavior:'smooth',block:'center'})}});


const bc=$('#builderClass'),bp=$('#builderProfession'),bh=$('#builderHomeland'),bs=$('#builderStyle');function updateBuilder(){if(!bc||!bp||!bh||!bs)return;$('#builderTitle').textContent=bc.value+' of '+bh.value;$('#builderSummary').textContent='A '+bc.value+' from '+bh.value+' following the '+bp.value+' profession with a '+bs.value+'-focused journey.';$('#builderTags').innerHTML=[bc.value,bp.value,bh.value,bs.value].map(x=>`<span>${x}</span>`).join('')}[bc,bp,bh,bs].filter(Boolean).forEach(x=>x.addEventListener('change',updateBuilder));updateBuilder();
if($('#developmentRegionGrid')){fetch('data/regions.json').then(r=>r.json()).then(d=>{const rows=Object.values(d.regions||{});$('#developmentRegionGrid').innerHTML=rows.map(r=>`<article class="development-card"><div class="region-card-top"><span class="region-icon">${r.icon||'◆'}</span><span class="region-state">${r.status}</span></div><h3>${r.name}</h3><p>${r.summary}</p><div class="region-card-progress"><i style="width:${r.completion}%"></i></div><div class="region-card-meta"><span>${r.completion}% complete</span><a class="text-link" href="world.html">Open atlas →</a></div></article>`).join('')})}
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');clearTimeout(window.__wrToast);window.__wrToast=setTimeout(()=>t.classList.remove('show'),2400)}
fetch('data/site.json').then(r=>r.json()).then(d=>{const set=(s,v)=>{$$(s).forEach(el=>el.textContent=v)};set('#serverStatus',d.serverStatus||'In Development');set('#mcVersion',d.minecraftVersion||'1.21');set('#bedrockStatus',d.bedrockSupported||'To Be Confirmed');set('#playerCount',(d.playerCount||'—')+' / '+(d.maxPlayers||'—'));const c=Number(d.worldCompletion)||0;set('#completionValue',c+'%');$$('#completionFill').forEach(el=>requestAnimationFrame(()=>el.style.width=c+'%'));if(d.serverAddress&&d.serverAddress!=='Coming Soon')set('#serverAddress',d.serverAddress);[['#discordJoin',d.discordUrl],['#pmcLink',d.planetMinecraftUrl],['#githubLink',d.githubUrl],['#githubCard',d.githubUrl]].forEach(([s,u])=>{$$(s).forEach(el=>{if(u)el.href=u})})}).catch(()=>{$$('#completionFill').forEach(el=>el.style.width='72%')});
$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const cat=btn.dataset.filter;$$('.quest-grid article').forEach(card=>card.classList.toggle('hidden-filter',cat!=='all'&&card.dataset.category!==cat))}));
$$('a[href]').forEach(a=>{const href=a.getAttribute('href');if(!href||href.startsWith('http')||href.startsWith('mailto:')||href.startsWith('#'))return;a.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||a.target==='_blank')return;e.preventDefault();if(!doors){location.href=href;return}document.body.classList.add('transitioning');setDoorMessage('TRAVELING THROUGH THE REALM');doors.classList.add('active','open','closing');doors.classList.remove('sealed','text-glow','flash');void doors.offsetWidth;requestAnimationFrame(()=>doors.classList.remove('open'));setTimeout(()=>doors.classList.add('sealed'),reduced?40:760);setTimeout(()=>doors.classList.add('text-glow'),reduced?60:980);setTimeout(()=>{try{sessionStorage.setItem('woodlandDoorArrival','1')}catch(_){}location.href=href},reduced?220:1500)})});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=$(a.getAttribute('href'));if(!target)return;e.preventDefault();target.scrollIntoView({behavior:'smooth'})}));


/* Restored hand-drawn leaf field from the BRASHEXODUS portfolio. */
(()=>{const assets=['broadleaf-01.png','broadleaf-02.png','broadleaf-03.png','broadleaf-04.png','broadleaf-05.png','broadleaf-06.png','spruce-a-01.png','spruce-a-02.png','spruce-a-03.png','spruce-a-04.png','spruce-a-05.png','spruce-b-01.png','spruce-b-02.png','spruce-b-03.png','spruce-b-04.png','spruce-b-05.png','spruce-c-01.png','spruce-c-02.png','spruce-c-03.png','spruce-c-04.png'];if(reduced||navigator.connection?.saveData===true||$('.custom-leaf-field'))return;const field=document.createElement('div');field.className='custom-leaf-field';field.setAttribute('aria-hidden','true');const compact=matchMedia('(max-width:760px)').matches,lowMemory=Number(navigator.deviceMemory||8)<=4,count=compact?12:lowMemory?16:22,frag=document.createDocumentFragment();for(let i=0;i<count;i++){const leaf=document.createElement('img'),size=compact?24+Math.random()*25:28+Math.random()*46,opacity=.38+Math.random()*.47,duration=13+Math.random()*17,delay=-(Math.random()*duration),startX=-6+Math.random()*106,drift=-120+Math.random()*240,sway=22+Math.random()*65,rotation=(Math.random()<.5?-1:1)*(300+Math.random()*620);leaf.className=`custom-leaf ${size>57?'is-near':size<37?'is-far':''}`;leaf.alt='';leaf.decoding='async';leaf.draggable=false;leaf.src=`assets/leaves/${assets[i%assets.length]}`;leaf.style.setProperty('--leaf-size',`${size.toFixed(1)}px`);leaf.style.setProperty('--leaf-opacity',opacity.toFixed(2));leaf.style.setProperty('--leaf-duration',`${duration.toFixed(2)}s`);leaf.style.setProperty('--leaf-delay',`${delay.toFixed(2)}s`);leaf.style.setProperty('--leaf-start-x',`${startX.toFixed(2)}vw`);leaf.style.setProperty('--leaf-drift',`${drift.toFixed(1)}px`);leaf.style.setProperty('--leaf-sway',`${sway.toFixed(1)}px`);leaf.style.setProperty('--leaf-rotation',`${rotation.toFixed(0)}deg`);frag.appendChild(leaf)}field.appendChild(frag);document.body.prepend(field);document.addEventListener('visibilitychange',()=>field.querySelectorAll('.custom-leaf').forEach(leaf=>leaf.style.animationPlayState=document.hidden?'paused':'running'));
if(matchMedia('(pointer:fine)').matches){let px=-9999,py=-9999,windRaf=0;const leaves=[...field.querySelectorAll('.custom-leaf')],radius=155;const applyWind=()=>{windRaf=0;for(const leaf of leaves){const r=leaf.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=cx-px,dy=cy-py,dist=Math.hypot(dx,dy);if(dist<radius){const force=(1-dist/radius),inv=dist?1/dist:1,wx=dx*inv*force*74,wy=dy*inv*force*48-18*force;leaf.style.setProperty('--mouse-wind-x',wx.toFixed(1)+'px');leaf.style.setProperty('--mouse-wind-y',wy.toFixed(1)+'px');leaf.style.setProperty('--mouse-wind-rot',(wx*.18).toFixed(1)+'deg')}else{leaf.style.setProperty('--mouse-wind-x','0px');leaf.style.setProperty('--mouse-wind-y','0px');leaf.style.setProperty('--mouse-wind-rot','0deg')}}};addEventListener('pointermove',e=>{px=e.clientX;py=e.clientY;if(!windRaf)windRaf=requestAnimationFrame(applyWind)},{passive:true});addEventListener('pointerleave',()=>{px=py=-9999;if(!windRaf)windRaf=requestAnimationFrame(applyWind)},{passive:true})}})();

/* Restored functional fantasy scrollbar. */
(()=>{const fine=matchMedia('(pointer:fine)');let bar,rail,thumb,dragging=false,dragOffset=0,raf=0;const maxScroll=()=>Math.max(0,document.documentElement.scrollHeight-innerHeight),travel=()=>Math.max(0,rail.clientHeight-thumb.offsetHeight),enabled=()=>fine.matches&&innerWidth>760&&maxScroll()>10;function update(){raf=0;if(!bar)return;const on=enabled();bar.hidden=!on;document.documentElement.classList.toggle('woodland-custom-scrollbar',on);if(!on)return;const y=(maxScroll()?Math.min(1,Math.max(0,scrollY/maxScroll())):0)*travel();thumb.style.transform=`translate(-50%, ${y}px)`}function req(){if(!raf)raf=requestAnimationFrame(update)}function fromPointer(y,smooth=false){const rect=rail.getBoundingClientRect(),t=travel();if(!t)return;const top=Math.min(t,Math.max(0,y-rect.top-dragOffset)),target=(top/t)*maxScroll();scrollTo({top:target,behavior:smooth&&!reduced?'smooth':'auto'})}function build(){if($('.woodland-fantasy-scrollbar'))return;bar=document.createElement('div');bar.className='woodland-fantasy-scrollbar';bar.setAttribute('aria-hidden','true');bar.innerHTML='<div class="woodland-fantasy-scrollbar__track"><div class="woodland-fantasy-scrollbar__rail"><div class="woodland-fantasy-scrollbar__thumb"></div></div></div>';document.body.appendChild(bar);rail=$('.woodland-fantasy-scrollbar__rail',bar);thumb=$('.woodland-fantasy-scrollbar__thumb',bar);thumb.addEventListener('pointerdown',e=>{if(!enabled())return;dragging=true;bar.classList.add('is-dragging');thumb.setPointerCapture(e.pointerId);dragOffset=e.clientY-thumb.getBoundingClientRect().top;e.preventDefault()});thumb.addEventListener('pointermove',e=>{if(dragging){fromPointer(e.clientY);e.preventDefault()}});const stop=e=>{if(!dragging)return;dragging=false;bar.classList.remove('is-dragging');try{thumb.releasePointerCapture(e.pointerId)}catch(_){}};thumb.addEventListener('pointerup',stop);thumb.addEventListener('pointercancel',stop);rail.addEventListener('pointerdown',e=>{if(e.target===thumb||!enabled())return;dragOffset=thumb.offsetHeight/2;fromPointer(e.clientY,true);e.preventDefault()});addEventListener('scroll',req,{passive:true});addEventListener('resize',req,{passive:true});new ResizeObserver(req).observe(document.documentElement);req()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',build,{once:true}):build()})();
})();