(()=>{const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];const loader=$('#loader'),fill=$('#loaderFill'),pct=$('#loaderPercent'),status=$('#loaderStatus'),doors=$('#doorTransition');
const phrases=['The woodland paths are awakening…','Lighting lanterns along the old road…','Opening the Grand Chronicle…','Calling travelers to the Realm Gate…','The realm is ready.'];
let n=0;const seen=sessionStorage.getItem('woodlandLoaderSeen')==='1';
function openDoors(removeAfter=true){if(!doors)return;doors.classList.add('active');doors.classList.remove('open');requestAnimationFrame(()=>requestAnimationFrame(()=>doors.classList.add('open')));setTimeout(()=>{document.body.classList.remove('transitioning');if(removeAfter){doors.classList.remove('active','open')}},1120)}
function revealRealm(){document.body.classList.remove('loading');document.body.classList.add('transitioning');if(loader){loader.classList.add('hidden');setTimeout(()=>loader.remove(),680)}openDoors(true)}
function finishLoader(){n=100;if(fill)fill.style.width='100%';if(pct)pct.textContent='100%';if(status)status.textContent=phrases[4];sessionStorage.setItem('woodlandLoaderSeen','1');setTimeout(revealRealm,420)}
if(loader){if(seen){loader.remove();document.body.classList.remove('loading');document.body.classList.add('transitioning');if(doors){doors.classList.add('active');setTimeout(()=>openDoors(true),80)}else document.body.classList.remove('transitioning')}else{if(doors){doors.classList.add('active');doors.classList.remove('open')}const t=setInterval(()=>{n=Math.min(96,n+Math.floor(Math.random()*5)+3);if(fill)fill.style.width=n+'%';if(pct)pct.textContent=n+'%';if(status)status.textContent=phrases[Math.min(3,Math.floor(n/24))];if(n>=96){clearInterval(t);setTimeout(finishLoader,220)}},105)}}else{document.body.classList.remove('loading');if(doors){document.body.classList.add('transitioning');doors.classList.add('active');setTimeout(()=>openDoors(true),60)}}
const cursor=$('#cursor');if(cursor&&matchMedia('(pointer:fine)').matches)addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});
const header=$('.site-header'),progress=$('#pageProgress');addEventListener('scroll',()=>{if(header)header.classList.toggle('compact',scrollY>30);if(progress){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%'}},{passive:true});
const menu=$('#menu'),nav=$('#nav');if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});$$('#nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}))}
const io=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});$$('.reveal').forEach(el=>io.observe(el));


let atlasRegions={},selectedRegionId=null,activeRegionFilter='all';
const atlasGrid=$('#regionGrid'),regionSearch=$('#regionSearch');
function regionHaystack(r){return [r.name,r.status,r.summary,r.description,...(r.settlements||[]),...(r.quests||[]),...(r.creatures||[]),...(r.resources||[]),...(r.features||[])].join(' ').toLowerCase()}
function selectRegion(id,openDetail=false){const r=atlasRegions[id];if(!r)return;selectedRegionId=id;$$('.map-pin').forEach(p=>p.classList.toggle('selected',p.dataset.regionId===id));$$('.region-card').forEach(c=>c.classList.toggle('selected',c.dataset.regionId===id));const title=$('#regionTitle'),text=$('#regionText'),status=$('#regionStatus'),tags=$('#regionFeatureTags'),open=$('#openSelectedRegion');if(title)title.textContent=r.name;if(text)text.textContent=r.summary;if(status)status.textContent=r.status+' • '+r.completion+'% complete';if(tags)tags.innerHTML=(r.features||[]).slice(0,5).map(x=>`<span>${x}</span>`).join('');if(open)open.disabled=false;if(openDetail)showRegionDetail(id);toast('Atlas selected: '+r.name)}
function listInto(sel,items){const el=$(sel);if(el)el.innerHTML=(items||[]).map(x=>`<li>${x}</li>`).join('')}
function showRegionDetail(id){const r=atlasRegions[id];const detail=$('#regionDetail');if(!r||!detail)return;$('#detailStatus').textContent=r.status;$('#detailName').textContent=(r.icon?r.icon+' ':'')+r.name;$('#detailDescription').textContent=r.description;$('#detailCompletion').textContent=r.completion+'%';$('#detailDanger').textContent='Danger: '+r.danger;requestAnimationFrame(()=>$('#detailCompletionFill').style.width=r.completion+'%');listInto('#detailSettlements',r.settlements);listInto('#detailQuests',r.quests);listInto('#detailCreatures',r.creatures);listInto('#detailResources',r.resources);$('#detailFeatures').innerHTML=(r.features||[]).map(x=>`<span>${x}</span>`).join('');$('#detailGallery').innerHTML=(r.gallery||[]).map((src,i)=>`<figure><img src="${src}" alt="${r.name} environment reference ${i+1}" loading="lazy"><figcaption>${r.name} • field view ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('');detail.hidden=false;detail.scrollIntoView({behavior:'smooth',block:'start'})}
function renderRegionGrid(){if(!atlasGrid)return;const q=(regionSearch?.value||'').trim().toLowerCase();const rows=Object.entries(atlasRegions).filter(([id,r])=>(activeRegionFilter==='all'||r.status===activeRegionFilter)&&(!q||regionHaystack(r).includes(q)));atlasGrid.innerHTML=rows.map(([id,r])=>`<article class="region-card ${selectedRegionId===id?'selected':''}" data-region-id="${id}" tabindex="0"><div class="region-card-top"><span class="region-icon">${r.icon||'◆'}</span><span class="region-state">${r.status}</span></div><h3>${r.name}</h3><p>${r.summary}</p><div class="region-card-progress"><i style="width:${r.completion}%"></i></div><div class="region-card-meta"><span>${r.completion}% built</span><span>Danger: ${r.danger}</span></div><div class="region-card-counts"><span>${(r.settlements||[]).length} settlements</span><span>${(r.quests||[]).length} quests</span><span>${(r.creatures||[]).length} creatures</span></div><button type="button" class="text-link region-card-open">View atlas entry →</button></article>`).join('');const count=$('#atlasResultCount');if(count)count.textContent=rows.length+' region'+(rows.length===1?'':'s');$$('.region-card',atlasGrid).forEach(card=>{const activate=()=>selectRegion(card.dataset.regionId,true);card.addEventListener('click',e=>{if(e.target.closest('button')||e.target===card)activate();else activate()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})});if(!rows.length)atlasGrid.innerHTML='<div class="atlas-empty"><strong>No paths found.</strong><span>Try a different search or development filter.</span></div>'}
if(atlasGrid||$$('.map-pin').length){fetch('data/regions.json').then(r=>r.json()).then(d=>{atlasRegions=d.regions||{};renderRegionGrid();$$('.map-pin').forEach(pin=>pin.addEventListener('click',()=>selectRegion(pin.dataset.regionId,false)));}).catch(()=>{if(atlasGrid)atlasGrid.innerHTML='<div class="atlas-empty"><strong>The atlas could not be opened.</strong><span>Check data/regions.json when testing locally.</span></div>'})}
if(regionSearch)regionSearch.addEventListener('input',renderRegionGrid);
$$('.region-filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.region-filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeRegionFilter=btn.dataset.regionFilter||'all';renderRegionGrid()}));
$('#openSelectedRegion')?.addEventListener('click',()=>selectedRegionId&&showRegionDetail(selectedRegionId));
$('#closeRegionDetail')?.addEventListener('click',()=>{const d=$('#regionDetail');if(d){d.hidden=true;$('.atlas-map')?.scrollIntoView({behavior:'smooth',block:'center'})}});


const bc=$('#builderClass'),bp=$('#builderProfession'),bh=$('#builderHomeland'),bs=$('#builderStyle');function updateBuilder(){if(!bc||!bp||!bh||!bs)return;$('#builderTitle').textContent=bc.value+' of '+bh.value;$('#builderSummary').textContent='A '+bc.value+' from '+bh.value+' following the '+bp.value+' profession with a '+bs.value+'-focused journey.';$('#builderTags').innerHTML=[bc.value,bp.value,bh.value,bs.value].map(x=>`<span>${x}</span>`).join('')}[bc,bp,bh,bs].filter(Boolean).forEach(x=>x.addEventListener('change',updateBuilder));updateBuilder();
if($('#developmentRegionGrid')){fetch('data/regions.json').then(r=>r.json()).then(d=>{const rows=Object.values(d.regions||{});$('#developmentRegionGrid').innerHTML=rows.map(r=>`<article class="development-card"><div class="region-card-top"><span class="region-icon">${r.icon||'◆'}</span><span class="region-state">${r.status}</span></div><h3>${r.name}</h3><p>${r.summary}</p><div class="region-card-progress"><i style="width:${r.completion}%"></i></div><div class="region-card-meta"><span>${r.completion}% complete</span><a class="text-link" href="world.html">Open atlas →</a></div></article>`).join('')})}
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');clearTimeout(window.__wrToast);window.__wrToast=setTimeout(()=>t.classList.remove('show'),2400)}
fetch('data/site.json').then(r=>r.json()).then(d=>{const set=(s,v)=>{$$(s).forEach(el=>el.textContent=v)};set('#serverStatus',d.serverStatus||'In Development');set('#mcVersion',d.minecraftVersion||'1.21');set('#bedrockStatus',d.bedrockSupported||'To Be Confirmed');set('#playerCount',(d.playerCount||'—')+' / '+(d.maxPlayers||'—'));const c=Number(d.worldCompletion)||0;set('#completionValue',c+'%');$$('#completionFill').forEach(el=>requestAnimationFrame(()=>el.style.width=c+'%'));if(d.serverAddress&&d.serverAddress!=='Coming Soon')set('#serverAddress',d.serverAddress);[['#discordJoin',d.discordUrl],['#pmcLink',d.planetMinecraftUrl],['#githubLink',d.githubUrl],['#githubCard',d.githubUrl]].forEach(([s,u])=>{$$(s).forEach(el=>{if(u)el.href=u})})}).catch(()=>{$$('#completionFill').forEach(el=>el.style.width='72%')});
$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const cat=btn.dataset.filter;$$('.quest-grid article').forEach(card=>card.classList.toggle('hidden-filter',cat!=='all'&&card.dataset.category!==cat))}));
$$('a[href]').forEach(a=>{const href=a.getAttribute('href');if(!href||href.startsWith('http')||href.startsWith('mailto:')||href.startsWith('#'))return;a.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||a.target==='_blank')return;e.preventDefault();if(!doors){location.href=href;return}document.body.classList.add('transitioning');doors.classList.add('active','open');requestAnimationFrame(()=>requestAnimationFrame(()=>doors.classList.remove('open')));setTimeout(()=>location.href=href,980)})});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=$(a.getAttribute('href'));if(!target)return;e.preventDefault();target.scrollIntoView({behavior:'smooth'})}));
})();